server:
  port: 8888
  servlet:
#    context-path: /fitconnect
    session:
      tracking-modes: cookie

# DB 접속 정보와 파일 업로드 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            redirect-uri: http://localhost:8888/login/oauth2/code/google
            scope:
            - email
            - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

# mybatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fitconnect.**